version: '3'
dotenv: ['../.env','.env']
vars:
  MODULE_NAME: "Logging App"

includes:
  version: ../Taskfile.version.yml
  production: ../Taskfile.prod.yml

tasks:
  default:
    desc: "Development build of {{.MODULE_NAME}}"

    cmds:
      - echo "Running..."
      - go vet ./...
      - task: format
      - wails dev -ldflags "-X main.version=Dev"

  update:
    cmds:
      - go get -u
      - go mod tidy
      - go mod verify
      - task: default

  format:
    dir: frontend
    cmds:
      - npm run format
      - npm run lint
